-- MySQL Script generated by MySQL Workbench
-- Sat Oct 17 16:02:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecoaccumulate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecoaccumulate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecoaccumulate` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecoaccumulate` ;

-- -----------------------------------------------------
-- Table `ecoaccumulate`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoaccumulate`.`city` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `City` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecoaccumulate`.`zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoaccumulate`.`zone` (
  `Zone ID` INT NOT NULL AUTO_INCREMENT,
  `Zone` VARCHAR(45) NULL DEFAULT NULL,
  `Cleanliness %` DECIMAL(45,0) NULL DEFAULT NULL,
  `city_ID` INT NOT NULL,
  PRIMARY KEY (`Zone ID`),
  INDEX `fk_zone_city1_idx` (`city_ID` ASC) VISIBLE,
  CONSTRAINT `fk_zone_city1`
    FOREIGN KEY (`city_ID`)
    REFERENCES `ecoaccumulate`.`city` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecoaccumulate`.`cleanliness drive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoaccumulate`.`cleanliness drive` (
  `CID` INT NOT NULL AUTO_INCREMENT,
  `NGO` VARCHAR(45) NULL DEFAULT NULL,
  `Event Name` VARCHAR(45) NULL DEFAULT NULL,
  `Expected Effectiveness` VARCHAR(45) NULL DEFAULT NULL,
  `Drive Date` VARCHAR(45) NULL DEFAULT NULL,
  `zone_Zone ID` INT NOT NULL,
  `Campaign Duration` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CID`),
  INDEX `fk_cleanliness drive_zone1_idx` (`zone_Zone ID` ASC) VISIBLE,
  CONSTRAINT `fk_cleanliness drive_zone1`
    FOREIGN KEY (`zone_Zone ID`)
    REFERENCES `ecoaccumulate`.`zone` (`Zone ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecoaccumulate`.`inspection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoaccumulate`.`inspection` (
  `Inspection ID` INT NOT NULL AUTO_INCREMENT,
  `Examiner` VARCHAR(45) NULL DEFAULT NULL,
  `Observed change %` VARCHAR(45) NULL DEFAULT NULL,
  `zone_Zone ID` INT NOT NULL,
  `Date` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Inspection ID`),
  INDEX `fk_inspection_zone1_idx` (`zone_Zone ID` ASC) VISIBLE,
  CONSTRAINT `fk_inspection_zone1`
    FOREIGN KEY (`zone_Zone ID`)
    REFERENCES `ecoaccumulate`.`zone` (`Zone ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
