# Generated by Django 3.2.6 on 2021-08-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('song', models.FileField(default='', upload_to='media')),
                ('artist', models.CharField(default='', max_length=1000)),
                ('img', models.ImageField(default=' ', upload_to='media')),
            ],
        ),
    ]
