# Generated by Django 3.2.6 on 2021-08-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
