# Generated by Django 3.2.6 on 2021-08-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
    ]
