# Generated by Django 3.2.6 on 2021-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_remove_contact_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='file',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
