# Generated by Django 3.2.6 on 2021-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20210811_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='desc',
            field=models.CharField(default='', max_length=500000),
        ),
    ]
