# Generated by Django 3.2.6 on 2021-08-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_rename_ml_id_web_web_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml',
            name='img',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='web',
            name='img',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
