# Generated by Django 3.2.6 on 2021-08-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_auto_20210812_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai',
            fields=[
                ('ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('algo', models.TextField(default='', max_length=900000)),
                ('img', models.ImageField(default='', upload_to='media')),
                ('video', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='app',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('algo', models.TextField(default='', max_length=900000)),
                ('img', models.ImageField(default='', upload_to='media')),
                ('video', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='dsa',
            fields=[
                ('dsa_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('algo', models.TextField(default='', max_length=900000)),
                ('img', models.ImageField(default='', upload_to='media')),
                ('video', models.URLField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='ml',
            name='algo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ml',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='web',
            name='algo',
            field=models.TextField(default='', max_length=900000),
        ),
    ]
