# Generated by Django 3.2.6 on 2021-08-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_alter_ml_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='img',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='app',
            name='img',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='img',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='web',
            name='img',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
