# Generated by Django 3.2.6 on 2021-08-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_auto_20210812_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='file',
            field=models.FileField(default='', upload_to='media'),
        ),
        migrations.AddField(
            model_name='dsa',
            name='file',
            field=models.FileField(default='', upload_to='media'),
        ),
        migrations.AddField(
            model_name='web',
            name='file',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
