# Generated by Django 3.2.6 on 2021-08-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_ai_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='password2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
