# Generated by Django 3.2.6 on 2021-08-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_auto_20210814_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='password2',
        ),
    ]
