# Generated by Django 3.2.6 on 2021-08-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_remove_contact_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsa',
            name='features',
            field=models.TextField(default='', max_length=900000),
        ),
        migrations.AddField(
            model_name='dsa',
            name='operations',
            field=models.TextField(default='', max_length=900000),
        ),
    ]
