# Generated by Django 3.2.6 on 2021-08-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
